CC = gcc

CFLAGS = -O0 -g -I. `sdl-config --cflags` -DUNIX -I../../Wrapper/SDL12
LDFLAGS = `sdl-config --libs` -lSDLmain -lSDL -lSDL_mixer -lSDL_image -lSDL_gfx -lSDL_ttf
OUTPUT = memory3ds

SOURCES = main.c graphics.c ../../Wrapper/SDL12/sf2d.c ../../Wrapper/SDL12/3ds.c
OBJS = ${SOURCES:.c=.o}

${OUTPUT}:${OBJS}
	${CC} -o ${OUTPUT} ${OBJS} ${CFLAGS} ${LDFLAGS} ${DEFINES} 
	
clean:
	rm *.o
	rm ${OUTPUT}
